nohup python preprocess.py --start 0 --split_num 48 --datas train --device 0 > logs/train_0.log 2>&1 &
nohup python preprocess.py --start 1 --split_num 48 --datas train --device 1 > logs/train_1.log 2>&1 &
nohup python preprocess.py --start 2 --split_num 48 --datas train --device 2 > logs/train_2.log 2>&1 &
nohup python preprocess.py --start 3 --split_num 48 --datas train --device 3 > logs/train_3.log 2>&1 &
nohup python preprocess.py --start 4 --split_num 48 --datas train --device 4 > logs/train_4.log 2>&1 &
nohup python preprocess.py --start 5 --split_num 48 --datas train --device 5 > logs/train_5.log 2>&1 &
nohup python preprocess.py --start 6 --split_num 48 --datas train --device 6 > logs/train_6.log 2>&1 &
nohup python preprocess.py --start 7 --split_num 48 --datas train --device 7 > logs/train_7.log 2>&1 &
nohup python preprocess.py --start 8 --split_num 48 --datas train --device 0 > logs/train_8.log 2>&1 &
nohup python preprocess.py --start 9 --split_num 48 --datas train --device 1 > logs/train_9.log 2>&1 &
nohup python preprocess.py --start 10 --split_num 48 --datas train --device 2 > logs/train_10.log 2>&1 &
nohup python preprocess.py --start 11 --split_num 48 --datas train --device 3 > logs/train_11.log 2>&1 &
nohup python preprocess.py --start 12 --split_num 48 --datas train --device 4 > logs/train_12.log 2>&1 &
nohup python preprocess.py --start 13 --split_num 48 --datas train --device 5 > logs/train_13.log 2>&1 &
nohup python preprocess.py --start 14 --split_num 48 --datas train --device 6 > logs/train_14.log 2>&1 &
nohup python preprocess.py --start 15 --split_num 48 --datas train --device 7 > logs/train_15.log 2>&1 &
nohup python preprocess.py --start 16 --split_num 48 --datas train --device 0 > logs/train_16.log 2>&1 &
nohup python preprocess.py --start 17 --split_num 48 --datas train --device 1 > logs/train_17.log 2>&1 &
nohup python preprocess.py --start 18 --split_num 48 --datas train --device 2 > logs/train_18.log 2>&1 &
nohup python preprocess.py --start 19 --split_num 48 --datas train --device 3 > logs/train_19.log 2>&1 &
nohup python preprocess.py --start 20 --split_num 48 --datas train --device 4 > logs/train_20.log 2>&1 &
nohup python preprocess.py --start 21 --split_num 48 --datas train --device 5 > logs/train_21.log 2>&1 &
nohup python preprocess.py --start 22 --split_num 48 --datas train --device 6 > logs/train_22.log 2>&1 &
nohup python preprocess.py --start 23 --split_num 48 --datas train --device 7 > logs/train_23.log 2>&1 &
nohup python preprocess.py --start 24 --split_num 48 --datas train --device 0 > logs/train_24.log 2>&1 &
nohup python preprocess.py --start 25 --split_num 48 --datas train --device 1 > logs/train_25.log 2>&1 &
nohup python preprocess.py --start 26 --split_num 48 --datas train --device 2 > logs/train_26.log 2>&1 &
nohup python preprocess.py --start 27 --split_num 48 --datas train --device 3 > logs/train_27.log 2>&1 &
nohup python preprocess.py --start 28 --split_num 48 --datas train --device 4 > logs/train_28.log 2>&1 &
nohup python preprocess.py --start 29 --split_num 48 --datas train --device 5 > logs/train_29.log 2>&1 &
nohup python preprocess.py --start 30 --split_num 48 --datas train --device 6 > logs/train_30.log 2>&1 &
nohup python preprocess.py --start 31 --split_num 48 --datas train --device 7 > logs/train_31.log 2>&1 &
nohup python preprocess.py --start 32 --split_num 48 --datas train --device 0 > logs/train_32.log 2>&1 &
nohup python preprocess.py --start 33 --split_num 48 --datas train --device 1 > logs/train_33.log 2>&1 &
nohup python preprocess.py --start 34 --split_num 48 --datas train --device 2 > logs/train_34.log 2>&1 &
nohup python preprocess.py --start 35 --split_num 48 --datas train --device 3 > logs/train_35.log 2>&1 &
nohup python preprocess.py --start 36 --split_num 48 --datas train --device 4 > logs/train_36.log 2>&1 &
nohup python preprocess.py --start 37 --split_num 48 --datas train --device 5 > logs/train_37.log 2>&1 &
nohup python preprocess.py --start 38 --split_num 48 --datas train --device 6 > logs/train_38.log 2>&1 &
nohup python preprocess.py --start 39 --split_num 48 --datas train --device 7 > logs/train_39.log 2>&1 &
nohup python preprocess.py --start 40 --split_num 48 --datas train --device 0 > logs/train_40.log 2>&1 &
nohup python preprocess.py --start 41 --split_num 48 --datas train --device 1 > logs/train_41.log 2>&1 &
nohup python preprocess.py --start 42 --split_num 48 --datas train --device 2 > logs/train_42.log 2>&1 &
nohup python preprocess.py --start 43 --split_num 48 --datas train --device 3 > logs/train_43.log 2>&1 &
nohup python preprocess.py --start 44 --split_num 48 --datas train --device 4 > logs/train_44.log 2>&1 &
nohup python preprocess.py --start 45 --split_num 48 --datas train --device 5 > logs/train_45.log 2>&1 &
nohup python preprocess.py --start 46 --split_num 48 --datas train --device 6 > logs/train_46.log 2>&1 &
nohup python preprocess.py --start 47 --split_num 48 --datas train --device 7 > logs/train_47.log 2>&1 &
nohup python preprocess.py --start 0 --split_num 8 --datas val --device 0 > logs/val_0.log 2>&1 &
nohup python preprocess.py --start 1 --split_num 8 --datas val --device 1 > logs/val_1.log 2>&1 &
nohup python preprocess.py --start 2 --split_num 8 --datas val --device 2 > logs/val_2.log 2>&1 &
nohup python preprocess.py --start 3 --split_num 8 --datas val --device 3 > logs/val_3.log 2>&1 &
nohup python preprocess.py --start 4 --split_num 8 --datas val --device 4 > logs/val_4.log 2>&1 &
nohup python preprocess.py --start 5 --split_num 8 --datas val --device 5 > logs/val_5.log 2>&1 &
nohup python preprocess.py --start 6 --split_num 8 --datas val --device 6 > logs/val_6.log 2>&1 &
nohup python preprocess.py --start 7 --split_num 8 --datas val --device 7 > logs/val_7.log 2>&1 &
nohup python preprocess.py --start 0 --split_num 8 --datas test --device 0 > logs/test_0.log 2>&1 &
nohup python preprocess.py --start 1 --split_num 8 --datas test --device 1 > logs/test_1.log 2>&1 &
nohup python preprocess.py --start 2 --split_num 8 --datas test --device 2 > logs/test_2.log 2>&1 &
nohup python preprocess.py --start 3 --split_num 8 --datas test --device 3 > logs/test_3.log 2>&1 &
nohup python preprocess.py --start 4 --split_num 8 --datas test --device 4 > logs/test_4.log 2>&1 &
nohup python preprocess.py --start 5 --split_num 8 --datas test --device 5 > logs/test_5.log 2>&1 &
nohup python preprocess.py --start 6 --split_num 8 --datas test --device 6 > logs/test_6.log 2>&1 &
nohup python preprocess.py --start 7 --split_num 8 --datas test --device 7 > logs/test_7.log 2>&1 &
